"use client";
import { useState } from 'react';
const Badge = ({ children, className, variant = "default" }) => (
    <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 ${className}`}>
        {children}
    </span>
);

export function AIConsultationReport({ analysis, loading }) {
    const [activeTab, setActiveTab] = useState('summary');

    if (loading) {
        return (
            <div className="w-full bg-white rounded-2xl border border-violet-100 shadow-sm overflow-hidden mt-6">
                <div className="p-6 border-b border-violet-100 bg-gradient-to-r from-violet-50/50 to-white flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-xl bg-violet-100 flex items-center justify-center animate-pulse">
                            <span className="text-2xl">🤖</span>
                        </div>
                        <div>
                            <h3 className="text-lg font-bold text-gray-900">Processing Post-Visit Analysis</h3>
                            <p className="text-sm text-violet-600">Please wait while the Clinical Intelligence Engine processes the session.</p>
                        </div>
                    </div>
                </div>
                <div className="p-8 space-y-6">
                    {/* Clearer Process Indication */}
                    <div className="space-y-4">
                        <div className="flex items-center gap-4 text-violet-700 font-medium">
                            <div className="w-6 h-6 rounded-full bg-violet-200 flex items-center justify-center text-xs">✓</div>
                            <span>Secure Room Terminated</span>
                        </div>
                        <div className="flex items-center gap-4 text-violet-700 font-semibold text-lg animate-pulse">
                            <div className="w-6 h-6 rounded-full border-2 border-violet-500 border-t-transparent animate-spin"></div>
                            <span>Transcribing Audio & Running Agentic Analysis (Cohere LLM)</span>
                        </div>
                        <div className="flex items-center gap-4 text-gray-400 font-medium">
                            <div className="w-6 h-6 rounded-full bg-gray-100 flex items-center justify-center text-xs">3</div>
                            <span>Generating Structured SOAP & Action Items</span>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    if (!analysis) return null;

    // Ensure analysis is an object
    const data = typeof analysis === 'string' ? JSON.parse(analysis) : analysis;

    if (data.error) {
        return (
            <div className="p-4 bg-red-50 border border-red-100 rounded-xl text-red-600 text-sm">
                Failed to load AI Analysis: {data.error}
            </div>
        );
    }

    return (
        <div className="w-full bg-white rounded-2xl border border-violet-200/60 shadow-sm overflow-hidden mt-6">
            {/* Header */}
            <div className="px-6 py-5 border-b border-violet-100 bg-gradient-to-r from-violet-50/80 to-white flex items-start sm:items-center justify-between flex-col sm:flex-row gap-4">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-violet-600 text-white flex items-center justify-center shadow-sm shadow-violet-200">
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-gray-900 tracking-tight">AI Consultation Report</h3>
                        <p className="text-sm text-violet-600 font-medium">Generated by Clinical Intelligence Engine</p>
                    </div>
                </div>
                <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 px-3 py-1 font-semibold shadow-sm">
                    ✓ Verified
                </Badge>
            </div>

            {/* Navigation */}
            <div className="flex border-b border-gray-100 px-2 overflow-x-auto hide-scrollbar">
                {[
                    { id: 'summary', name: 'Clinical Summary', icon: '📝' },
                    { id: 'action', name: 'Action Items', icon: '⚡' },
                ].map((tab) => (
                    <button
                        key={tab.id}
                        onClick={() => setActiveTab(tab.id)}
                        className={`flex items-center gap-2 px-4 py-3 text-sm font-semibold border-b-2 transition-colors whitespace-nowrap ${activeTab === tab.id
                            ? 'border-violet-600 text-violet-700'
                            : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-200'
                            }`}
                    >
                        <span>{tab.icon}</span>
                        {tab.name}
                    </button>
                ))}
            </div>

            {/* Content */}
            <div className="p-6 bg-[#FAFAFA]">
                {activeTab === 'summary' && (
                    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-300">
                        <section>
                            <h4 className="flex items-center gap-2 text-base font-bold text-gray-900 uppercase tracking-wider mb-4">
                                <span className="w-2 h-2 rounded-full bg-violet-600"></span>
                                Objective Summary
                            </h4>
                            <p className="text-gray-800 leading-relaxed text-lg bg-white p-6 rounded-xl border border-gray-200/60 shadow-sm">
                                {data.clinical_summary}
                            </p>
                        </section>

                        <section>
                            <h4 className="flex items-center gap-2 text-base font-bold text-gray-900 uppercase tracking-wider mb-4">
                                <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                                Key Takeaways
                            </h4>
                            <ul className="space-y-4">
                                {data.key_takeaways?.map((point, idx) => (
                                    <li key={idx} className="flex gap-4 text-gray-800 bg-white p-5 rounded-xl border border-gray-200/60 shadow-sm items-start">
                                        <span className="text-blue-500 mt-1 flex-shrink-0">
                                            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                                <path d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" />
                                            </svg>
                                        </span>
                                        <span className="text-lg font-medium">{point}</span>
                                    </li>
                                ))}
                            </ul>
                        </section>
                    </div>
                )}

                {activeTab === 'action' && (
                    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

                            {/* Patient Actions */}
                            <div>
                                <h4 className="flex items-center gap-2 text-base font-bold text-gray-900 uppercase tracking-wider mb-4">
                                    <span className="text-2xl">👤</span> Patient Actions
                                </h4>
                                <div className="space-y-4">
                                    {data.action_items?.filter(item => item.assignee === 'patient').length > 0 ? (
                                        data.action_items.filter(item => item.assignee === 'patient').map((task, idx) => (
                                            <div key={idx} className="p-5 bg-white rounded-xl border border-gray-200 shadow-sm flex items-start gap-4">
                                                <input type="checkbox" className="mt-1.5 w-5 h-5 text-violet-600 rounded border-gray-300" />
                                                <div>
                                                    <p className="text-gray-900 font-medium text-base leading-snug">{task.task}</p>
                                                    {task.urgency === 'high' && <Badge className="mt-3 bg-red-100 text-red-700 border-none px-3 py-1 text-xs">High Priority</Badge>}
                                                </div>
                                            </div>
                                        ))
                                    ) : (
                                        <div className="p-5 bg-gray-50 rounded-xl border border-gray-200 border-dashed text-gray-500 text-base text-center">
                                            No patient actions required.
                                        </div>
                                    )}
                                </div>
                            </div>

                            {/* Provider Actions */}
                            <div>
                                <h4 className="flex items-center gap-2 text-base font-bold text-gray-900 uppercase tracking-wider mb-4">
                                    <span className="text-2xl">🩺</span> Provider Actions
                                </h4>
                                <div className="space-y-4">
                                    {data.action_items?.filter(item => item.assignee === 'provider').length > 0 ? (
                                        data.action_items.filter(item => item.assignee === 'provider').map((task, idx) => (
                                            <div key={idx} className="p-5 bg-violet-50 rounded-xl border border-violet-100 shadow-sm flex items-start gap-4">
                                                <div className="p-1.5 bg-violet-200 rounded text-violet-700 mt-0.5">
                                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                                                </div>
                                                <div>
                                                    <p className="text-violet-950 font-semibold text-base leading-snug">{task.task}</p>
                                                    {task.urgency === 'high' && <Badge className="mt-3 bg-red-100 text-red-700 border-none px-3 py-1 text-xs">Needs immediate attention</Badge>}
                                                </div>
                                            </div>
                                        ))
                                    ) : (
                                        <div className="p-5 bg-gray-50 rounded-xl border border-gray-200 border-dashed text-gray-500 text-base text-center">
                                            No provider actions required.
                                        </div>
                                    )}
                                </div>
                            </div>

                        </div>

                        {data.recommended_follow_up && (
                            <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-100 shadow-sm flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                    <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center shadow-sm text-blue-600">
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                                    </div>
                                    <div>
                                        <p className="text-xs text-blue-600 font-bold uppercase tracking-wider">Follow Up</p>
                                        <p className="text-sm font-semibold text-gray-900">Recommended in {data.recommended_follow_up}</p>
                                    </div>
                                </div>
                                <button className="px-4 py-2 bg-white text-blue-700 text-sm font-semibold rounded-lg shadow-sm border border-blue-200 hover:bg-blue-50 transition-colors">
                                    Schedule Now
                                </button>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
